outpkg: "{{.PackageName}}_mock"
with-expecter: true
packages:
  github.com/harnyk/listman/pkg/importservice:
    interfaces:
      ImportService:
  github.com/harnyk/listman/pkg/aiservice:
    interfaces:
      AIService:
  github.com/harnyk/listman/pkg/botservice:
    interfaces:
      TgAPI:
