/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ItemItemIdLazyImport = createFileRoute('/item/$itemId')()
const ImportsListIdLazyImport = createFileRoute('/imports/$listId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ItemItemIdLazyRoute = ItemItemIdLazyImport.update({
  path: '/item/$itemId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/item.$itemId.lazy').then((d) => d.Route))

const ImportsListIdLazyRoute = ImportsListIdLazyImport.update({
  path: '/imports/$listId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/imports.$listId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/imports/$listId': {
      preLoaderRoute: typeof ImportsListIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/item/$itemId': {
      preLoaderRoute: typeof ItemItemIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ImportsListIdLazyRoute,
  ItemItemIdLazyRoute,
])

/* prettier-ignore-end */
