name: On Release

on:
  # release:
  #   types:
  #     - published
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/_test.yaml
  deploy_prod:
    needs:
      - test
    uses: ./.github/workflows/_deploy.yaml
    with:
      token: ${{ secrets.VERCEL_TOKEN }}
